diary/urls.py
from django.urls import path
from . import views
app_name = 'diary'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('user_login/', views.User_LoginView.as_view(), name='user_login'),
    path('company_login/', views.Company_LoginView.as_view(), name='company_login'),
    path('user_entry/', views.User_EntryView.as_view(), name='user_entry'),
    path('user_detail/', views.User_DetailView.as_view(), name='user_detail'),
    path('company_entry/', views.Company_EntryView.as_view(), name='company_entry'),
    path('company_detail/', views.Company_DetailView.as_view(), name='company_detail'),
    path('service_entry/', views.Service_EntryView.as_view(), name='service_entry'),
    path('service_detail/', views.Service_DetailView.as_view(), name='service_detail'),
    path('post_entry/', views.Post_EntryView.as_view(), name='post_entry'),
    path('post_detail/', views.Post_DetailView.as_view(), name='post_detail'),
    path('post_finish/', views.Post_FinishView.as_view(), name='post_finish'),
    path('after_login/', views.After_LoginView.as_view(), name='after_login'),
# {% url 'diary:' %}
]



'''
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),

]
'''

private_diary/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('diary.urls')),
]

diary/models.py
from django.db import models

# Create your models here.

diary/views.py
from django.views import generic
from django.shortcuts import render


class IndexView(generic.TemplateView):
    template_name = "index.html"

class SearchView(generic.TemplateView):
    template_name = "search.html"

class User_LoginView(generic.TemplateView):
    template_name = "user_login.html"

class Company_LoginView(generic.TemplateView):
    template_name = "company_login.html"
    
class User_EntryView(generic.TemplateView):
    template_name = "user_entry.html"
    
class User_DetailView(generic.TemplateView):
    template_name = "user_detail.html"
    
class Company_EntryView(generic.TemplateView):
    template_name = "company_entry.html"
    
class Company_DetailView(generic.TemplateView):
    template_name = "company_detail.html"
    
class Service_EntryView(generic.TemplateView):
    template_name = "service_entry.html"
    
class Service_DetailView(generic.TemplateView):
    template_name = "service_detail.html"
    
class Post_EntryView(generic.TemplateView):
    template_name = "post_entry.html"
    
class Post_DetailView(generic.TemplateView):
    template_name = "post_detail.html"

class Post_FinishView(generic.TemplateView):
    template_name = "post_finish.html"
    
class After_LoginView(generic.TemplateView):
    template_name = "after_login.html" 

diary/templates/after_login.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>卒業研究</title>
  <link href="{% static 'css/reset.css' %}" rel="stylesheet"/>
  <link href="{% static 'css/style.css' %}" rel="stylesheet"/>
</head>
<body>
    <header class=" header">
        <div class="header_content wrapper">
            <h1><a href="{% url 'diary:index' %}">タイトル</a></h1>
            <ul class="ulflex">
                <li><a href="{% url 'diary:company_detail' %}">アカウントページへ</a></li>
                <li><a href="{% url 'diary:service_entry' %}">サービス作成ページへ</a></li>
                <li><a href="#">ログアウト</a></li>
            </ul>
        </div>
    </header>
<!-- {% block contents %}
{% endblock %} -->
</body>
</html>

diary/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>卒業研究</title>
  <link href="{% static 'css/reset.css' %}" rel="stylesheet"/>
  <link href="{% static 'css/style.css' %}" rel="stylesheet"/>
</head>
<body>
    <header class=" header">
        <div class="header_content wrapper">
            <h1><a href="{% url 'diary:index' %}">タイトル</a></h1>
            <ul class="ulflex">
                <li><a href="{% url 'diary:user_entry' %}">新規利用者登録</a></li>
                <li><a href="{% url 'diary:company_entry' %}">新規事業者登録</a></li>
                <li><a href="{% url 'diary:company_login' %}">事業者用ログイン</a></li>
                <li><a href="{% url 'diary:user_login' %}">依頼者用ログイン</a></li>
            </ul>
        </div>
    </header>
{% block contents %}
{% endblock %}
</body>
</html>

diary/templates/company_detail.html
{% extends 'base.html' %}
{% load static %}
{% block contents %}
  <section class="wrapper">
    <img class="account_image" src="{% static 'assets/main.jpg' %}" alt="#">
    <div class="account_flex">  
      <img class="account_icon" src="{% static 'assets/main.jpg' %}" alt="#">
      <div>
        <p>名前</p>
        <p>キャッチコピー</p>
      </div>
    </div>
    <h2 class="account_subtitle">自己紹介</h2>
    <p>テキスト</p>
    <p>テキスト</p>
    <p>テキスト</p>
    <p>テキスト</p>
    <h2 class="account_subtitle">実績</h2>
    <p>他のサービス履歴</p>
    <p>他のサービス履歴</p>
    <p>他のサービス履歴</p>
    <p>他のサービス履歴</p>
    <p>他のサービス履歴</p>
  </section>
{% endblock %}

diary/templates/company_entry.html
{% extends 'base.html' %}
{% block contents %}
  <section class="wrapper">
    <h2 class="entry_title">新規事業者登録</h2>
    <dl class="entry_form">
      <dt>名前<span class="entry_required">必須</span></dt>
      <dd><input class="entry_input" type="text"></dd>
      <dt>読み仮名<span class="entry_required">必須</span></dt>
      <dd><input class="entry_input" type="text"></dd>
      <dt>メールアドレス<span class="entry_required">必須</span></dt>
      <dd><input class="entry_input" type="text"></dd>
      <dt>パスワード<span class="entry_required">必須</span></dt>
      <dd><input class="entry_input" type="password"></dd>
    </dl>
    <div class="entry_button">
      <button type="submit">登録する</button>
    </div>
  </section>
{% endblock %}

diary/templates/company_login.html
{% extends 'base.html' %}
{% block contents %}
  <section>
    <div class="login wrapper">
      <h2>事業者ログイン</h2>
      <form>
        <div class="login_input">
          <p>メールアドレス</p>
          <input type="text">
        </div>
        <div class="login_input">
          <p>パスワード</p>
          <input type="password">
        </div>
        <div class="login_button">
          <button type="submit">ログイン</button>
        </div>
      </form>
    </div>
  </section>
{% endblock %}

diary/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block contents %}
  <section>
    <img src="{% static 'assets/main.jpg' %}" alt="#">
  </section>

  <section class="wrapper">
    <h2 class="index_subtitle">検索</h2>
    <ul class="index_flex">
      <li>
        <a href="{% url 'diary:search' %}">
          ジャンル
        </a>
      </li>
      <li><a href="{% url 'diary:search' %}">ジャンル</a></li>
      <li><a href="{% url 'diary:search' %}">ジャンル</a></li>
      <li><a href="{% url 'diary:search' %}">ジャンル</a></li>
      <li><a href="{% url 'diary:search' %}">ジャンル</a></li>
      <li><a href="{% url 'diary:search' %}">ジャンル</a></li>
      <li><a href="{% url 'diary:search' %}">ジャンル</a></li>
      <li><a href="{% url 'diary:search' %}">ジャンル</a></li>
      <li><a href="{% url 'diary:search' %}">ジャンル</a></li>
      <li><a href="{% url 'diary:search' %}">ジャンル</a></li>
    </ul>
    <input type="text">
    <button>検索</button>
  </section>
  
  <section class="wrapper">
    <h2 class="index_subtitle">新着</h2>
    <ul class="index_news">
      <li>
        <a href="{% url 'diary:service_detail' %}">
          <img src="{% static 'assets/main.jpg' %}" alt="#">
          <p>サービス名</p>
          <p>事業者名</p>
          <p>カテゴリ</p>
          <p>サムネイル用概要</p>
        </a>
      </li>
      <li>
        <a href="{% url 'diary:service_detail' %}">
          <img src="{% static 'assets/main.jpg' %}" alt="#">
          <p>サービス名</p>
          <p>事業者名</p>
          <p>カテゴリ</p>
          <p>サムネイル用概要</p>
        </a>
      </li>
      <li>
        <a href="{% url 'diary:service_detail' %}">
          <img src="{% static 'assets/main.jpg' %}" alt="#">
          <p>サービス名</p>
          <p>事業者名</p>
          <p>カテゴリ</p>
          <p>サムネイル用概要</p>
        </a>
      </li>
      <li>
        <a href="{% url 'diary:service_detail' %}">
          <img src="{% static 'assets/main.jpg' %}" alt="#">
          <p>サービス名</p>
          <p>事業者名</p>
          <p>カテゴリ</p>
          <p>サムネイル用概要</p>
        </a>
      </li>
    </ul>
  </section>
{% endblock %}

diary/templates/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% block contents %}

  <section class="wrapper">
    <h2>サービス詳細</h2>
    <div class="service_flex">
      <img src="{% static 'assets/fee.jpg' %}" alt="#">
      <ul class="post_list">
        <li>サービス名</li>
        <li>サービスのカテゴリ</li>
        <li>金額</li>
      </ul>
    </div>
    <div class="post_detail">
      <h3>概要</h3>
      <p>テキスト</p>
      <p>テキスト</p>
      <p>テキスト</p>
      <p>テキスト</p>
    </div>
    <div class="offer_button">
      <a href="{% url 'diary:post_finish' %}">申し込む</a>
    </div>
  </section>
{% endblock %}

diary/templates/post_finish.html
{% extends 'base.html' %}
{% block contents %}
  <section class="wrapper">
    <p class="post_finish">申し込みが完了しました<br>少々お待ちください</p>
    <div class="finish_button">
      <a href="{% url 'diary:index' %}">Topに戻る</a>
    </div>
    </section>
{% endblock %}

diary/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block contents %}
  <section class="wrapper">
    <h1>サービスを探す</h1>
    <input type="text">
    <button>検索</button>
    <ul class="search_flex">
      <li>
        <a href="{% url 'diary:service_detail' %}">
          <img src="{% static 'assets/main.jpg' %}" alt="#">
          <p>サービス名</p>
          <p>事業者名</p>
          <p>カテゴリ</p>
          <p>サムネイル用概要</p>
        </a>
      </li>
      <li>
        <a href="{% url 'diary:service_detail' %}">
          <img src="{% static 'assets/main.jpg' %}" alt="#">
          <p>サービス名</p>
          <p>事業者名</p>
          <p>カテゴリ</p>
          <p>サムネイル用概要</p>
        </a>
      </li>
      <li>
        <a href="{% url 'diary:service_detail' %}">
          <img src="{% static 'assets/main.jpg' %}" alt="#">
          <p>サービス名</p>
          <p>事業者名</p>
          <p>カテゴリ</p>
          <p>サムネイル用概要</p>
        </a>
      </li>
      <li>
        <a href="{% url 'diary:service_detail' %}">
          <img src="{% static 'assets/main.jpg' %}" alt="#">
          <p>サービス名</p>
          <p>事業者名</p>
          <p>カテゴリ</p>
          <p>サムネイル用概要</p>
        </a>
      </li>
      <li>
        <a href="{% url 'diary:service_detail' %}">
          <img src="{% static 'assets/main.jpg' %}" alt="#">
          <p>サービス名</p>
          <p>事業者名</p>
          <p>カテゴリ</p>
          <p>サムネイル用概要</p>
        </a>
      </li>
      <li>
        <a href="{% url 'diary:service_detail' %}">
          <img src="{% static 'assets/main.jpg' %}" alt="#">
          <p>サービス名</p>
          <p>事業者名</p>
          <p>カテゴリ</p>
          <p>サムネイル用概要</p>
        </a>
      </li>
    </ul>
  </section>
{% endblock %}

diary/templates/service_detail.html
{% extends 'base.html' %}
{% load static %}
{% block contents %}
  <section class="wrapper">
    <h1 class="sarvice_title">サービス名</h1>
    <img src="{% static 'assets/main.jpg' %}" alt="#">
    <h2 class="service_explanaton">サービスについて</h2>
    <p>ooなさーびすです</p>
    <p>ooなさーびすです</p>
    <p>ooなさーびすです</p>
    <p>ooなさーびすです</p>
    <h3>サービスを探す</h3>
    <input type="text">
    <button type="submit">検索</button>
    <h3>新着</h3>
    <ul class="service_list">
      <li>
        <a href="{% url 'diary:post_detail' %}">
          <img src="{% static 'assets/fee.jpg' %}" alt="#">
          <p>投稿名</p>
          <p>事業者名</p>
          <p>料金</p>
          <p>サムネイル用概要</p>
        </a>
      </li>
      <li>
        <a href="{% url 'diary:post_detail' %}">
          <img src="{% static 'assets/fee.jpg' %}" alt="#">
          <p>投稿名</p>
          <p>事業者名</p>
          <p>料金</p>
          <p>サムネイル用概要</p>
        </a>
      </li>
      <li>
        <a href="{% url 'diary:post_detail' %}">
          <img src="{% static 'assets/fee.jpg' %}" alt="#">
          <p>投稿名</p>
          <p>事業者名</p>
          <p>料金</p>
          <p>サムネイル用概要</p>
        </a>
      </li>
      <li>
        <a href="{% url 'diary:post_detail' %}">
          <img src="{% static 'assets/fee.jpg' %}" alt="#">
          <p>投稿名</p>
          <p>事業者名</p>
          <p>料金</p>
          <p>サムネイル用概要</p>
        </a>
      </li>
      <li>
        <a href="{% url 'diary:post_detail' %}">
          <img src="{% static 'assets/fee.jpg' %}" alt="#">
          <p>投稿名</p>
          <p>事業者名</p>
          <p>料金</p>
          <p>サムネイル用概要</p>
        </a>
      </li>
      <li>
        <a href="{% url 'diary:post_detail' %}">
          <img src="{% static 'assets/fee.jpg' %}" alt="#">
          <p>投稿名</p>
          <p>事業者名</p>
          <p>料金</p>
          <p>サムネイル用概要</p>
        </a>
      </li>
      <li>
        <a href="{% url 'diary:post_detail' %}">
          <img src="{% static 'assets/fee.jpg' %}" alt="#">
          <p>投稿名</p>
          <p>事業者名</p>
          <p>料金</p>
          <p>サムネイル用概要</p>
        </a>
      </li>
    </ul>
  </section>
{% endblock %}

diary/templates/service_entry.html
{% extends 'base.html' %}
{% block contents %}

  <section class="wrapper">
    <h2>サービス作成</h2>
    <form action="">
      <dl>
        <dt>サービス名</dt>
        <dd><input type="text"></dd>
        <dt>概要</dt>
        <dd><textarea name="#" id="#" cols="30" rows="10"></textarea></dd>
        <dt>画像</dt>
        <dd><input type="file"></dd>
        <dt>サービスのカテゴリ</dt>
        <dd><input type="text"></dd>
      </dl>
      <button type="submit">登録する</button>
    </form>
  </section>
{% endblock %}

diary/templates/user_detail.html
{% extends 'base.html' %}
{% block contents %}

  <section>
    <img src="" alt="">
    <img src="" alt="">
    <p>名前</p>
    <p>キャッチコピー</p>
    <p>自己紹介</p>
    <p>テキスト</p>
    <p>テキスト</p>
    <p>テキスト</p>
    <p>テキスト</p>
    <h2>実績</h2>
    <p>他のサービス履歴</p>
  </section>
{% endblock %}

diary/templates/user_entry.html
{% extends 'base.html' %}
{% block contents %}
<section class="wrapper">
  <h2 class="entry_title">新規利用者登録</h2>
  <dl class="entry_form">
    <dt>名前<span class="entry_required">必須</span></dt>
    <dd><input class="entry_input" type="text"></dd>
    <dt>読み仮名<span class="entry_required">必須</span></dt>
    <dd><input class="entry_input" type="text"></dd>
    <dt>メールアドレス<span class="entry_required">必須</span></dt>
    <dd><input class="entry_input" type="text"></dd>
    <dt>パスワード<span class="entry_required">必須</span></dt>
    <dd><input class="entry_input" type="password"></dd>
  </dl>
  <div class="entry_button">
    <button type="submit">登録する</button>
  </div>
</section>
{% endblock %}

diary/templates/user_login.html
{% extends 'base.html' %}
{% block contents %}

  <section>
    <div class="login wrapper">
      <h2>利用者ログイン</h2>
      <form>
        <div class="login_input">
          <p>メールアドレス</p>
          <input type="text">
        </div>
        <div class="login_input">
          <p>パスワード</p>
          <input type="password">
        </div>
        <div class="login_button">
          <button type="submit">ログイン</button>
        </div>
      </form>
    </div>
  </section>
{% endblock %}